### ISSUE TITLE
Printempty

### ISSUE THREAD

**Issue by numtaro** [rsennrich/Bleualign#30]
Bleualign doesn't work when '--printempty' is used. Without this option works just fine but I'd like to see the unaligned sentences.
```
Traceback (most recent call last):
  File "bleualign.py", line 15, in <module>
    a.mainloop()
  File "/home/numtaro/Downloads/Bleualign/bleualign/align.py", line 273, in mainloop
    self.printout(sourcelist, translist, targetlist)
  File "/home/numtaro/Downloads/Bleualign/bleualign/align.py", line 976, in printout
    self.out1.writelines([line + '\n' for line in sources])
TypeError: must be unicode, not str
```

**Comment by rsennrich** [comment]
thanks; this has been fixed.
